[build]
  command = "npm install --registry=https://registry.npmjs.org/ && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  NPM_CONFIG_REGISTRY = "https://registry.npmjs.org/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
